/* ============================================================
   ZurVault cover-artist map — shared by artists.html and artist.html.
   Same pattern as character-map.js and collections-map.js, but this one
   is fully mechanical rather than hand-curated: generated by querying
   Magic Eden's per-collection listings endpoint for every symbol in
   DC_COLLECTIONS (index.html) and reading the `Cover Artist` attribute
   off one sample listing per collection. Cover Artist is a print-run-level
   attribute (every copy of the same comic issue shares the same credits),
   not a per-individual-token attribute like Rarity, so a static
   collection->artist mapping is accurate here the way it wouldn't be for
   something that varies copy-to-copy.

   Multi-artist credits (e.g. "Leandro Fernandez, Dave McCaig") are split
   into separate entries, one per named artist, so a collection with two
   credited cover artists shows up under both. Name-suffix fragments
   (", Jr.", ", Sr.", ", II"/"III"/"IV") are kept attached to the
   preceding name rather than split into their own bogus entry — an early
   pass without that fix produced a standalone "Jr." artist from
   "Romulo Fajardo, Jr.". A handful of casing/diacritic variants seen in
   the raw data were merged by hand ("HI-FI"/"Hi-Fi", "George
   Perez"/"George Pérez", "Stjepan Sejic"/"Šejić").

   16 tracked collections have no Cover Artist attribute at all and are
   absent from every entry below — all non-comic collectibles (patches,
   masks, promo boxes, MAD Magazine, mystery-box packs), the same category
   character-map.js already excludes as "not comics." Two placeholder
   values ("NA", "Various") were dropped rather than treated as artist
   names.

   This snapshot is only as fresh as whenever it was last regenerated —
   Cover Artist doesn't change for an existing collection, but newly added
   DC_COLLECTIONS entries won't appear here until this file is
   regenerated against them.

   To add a new artist page: this file is meant to be regenerated
   wholesale from live data rather than hand-edited entry-by-entry: query
   `{symbol}/listings?limit=1` for every DC_COLLECTIONS symbol, pull
   `token.attributes` -> "Cover Artist", group by (cleaned) artist name.
   ============================================================ */
const ARTIST_MAP = {
  "alex-sinclair": {
    name: "Alex Sinclair",
    symbols: ["blackest_night_20092010_1", "batman_19402011_428", "flashpoint_2011_1", "dc3_super_power_packs_series_justice_league_vs_suicide_squad", "batman_2016_160", "harley_quinn_20002004_1", "batman_19402011_610", "batman_19402011_608", "batman_2016_159_ashcan_special_edition", "batman_608_multiverse_edition"],
  },
  "murphy-anderson": {
    name: "Murphy Anderson",
    symbols: ["the_flash_123_multiverse_edition", "superman_19392011_199", "batman_19402011_181", "the_brave_and_the_bold_19551983_67", "justice_league_of_america_19601987_1", "the_flash_19591985_123", "hawkman_19641968_4", "the_brave_and_the_bold_19551983_28", "green_lantern_19601986_59"],
  },
  "carmine-infantino": {
    name: "Carmine Infantino",
    symbols: ["the_flash_123_multiverse_edition", "superman_19392011_199", "showcase_19561978_4", "batman_19402011_181", "the_brave_and_the_bold_19551983_67", "the_flash_19591985_123", "the_flash_19591985_105"],
  },
  "jim-lee": {
    name: "Jim Lee",
    symbols: ["justice_league_20112016_1", "batman_2016_160", "batman_2016_158", "batman_19402011_610", "batman_19402011_608", "batman_2016_159_ashcan_special_edition", "batman_608_multiverse_edition"],
  },
  "george-perez": {
    name: "George Pérez",
    symbols: ["dc3_super_power_packs_series_2_crisis_on_infinite_earths", "tales_of_the_teen_titans_19801988_44", "the_new_teen_titans_19801988_1", "dc3_super_power_packs_series_1_crisis_on_infinite_earths", "dc_comics_presents_19781986_26", "crisis_on_infinite_earths"],
  },
  "scott-williams": {
    name: "Scott Williams",
    symbols: ["batman_2016_160", "batman_2016_158", "batman_19402011_610", "batman_19402011_608", "batman_2016_159_ashcan_special_edition", "batman_608_multiverse_edition"],
  },
  "bob-kane": {
    name: "Bob Kane",
    symbols: ["detective_comics_19372011_38", "batman_19402011_5", "batman_19402011_1", "detective_comics_19372011_31", "detective_comics_1937_40"],
  },
  "gaspar-saladino": {
    name: "Gaspar Saladino",
    symbols: ["dc3_super_power_packs_series_2_crisis_on_infinite_earths", "tales_of_the_teen_titans_19801988_44", "the_new_teen_titans_19801988_1", "dc3_super_power_packs_series_1_crisis_on_infinite_earths", "dc_comics_presents_19781986_26"],
  },
  "david-mazzucchelli": {
    name: "David Mazzucchelli",
    symbols: ["batman_19402011_405", "batman_19402011_406", "batman_year_one", "batman_19402011_407"],
  },
  "ivan-reis": {
    name: "Ivan Reis",
    symbols: ["the_flash_123_multiverse_edition", "blackest_night_20092010_1", "dc3_super_power_packs_series_aquaman", "aquaman_2025_1"],
  },
  "jerry-robinson": {
    name: "Jerry Robinson",
    symbols: ["detective_comics_19372011_38", "batman_19402011_1", "detective_comics_19372011_58", "the_flash_the_fastest_man_alive_2022_1"],
  },
  "andy-kubert": {
    name: "Andy Kubert",
    symbols: ["flashpoint_2011_1", "superman_2023_1", "batman_19402011_655"],
  },
  "dan-jurgens": {
    name: "Dan Jurgens",
    symbols: ["justice_league_unlimited_2024_6", "summer_of_superman_special_2025_1", "superman_19872006_75"],
  },
  "dan-mora": {
    name: "Dan Mora",
    symbols: ["superman_unlimited_2025_1", "dc3_super_power_packs_series_absolute_power", "immortal_legend_batman_2025_1"],
  },
  "frank-martin": {
    name: "Frank Martin",
    symbols: ["absolute_batman_2024_5", "absolute_batman_2024_9", "absolute_batman_2024_3"],
  },
  "greg-capullo": {
    name: "Greg Capullo",
    symbols: ["dceased_2019_1", "batman_20112016_5", "batman_vol_1_the_court_of_owls"],
  },
  "hi-fi": {
    name: "Hi-Fi",
    symbols: ["justice_league_unlimited_2024_1", "justice_league_unlimited_2024_6", "summer_of_superman_special_2025_1"],
  },
  "nick-dragotta": {
    name: "Nick Dragotta",
    symbols: ["absolute_batman_2024_5", "absolute_batman_2024_9", "absolute_batman_2024_3"],
  },
  "sheldon-moldoff": {
    name: "Sheldon Moldoff",
    symbols: ["flash_comics_19401949_1", "the_flash_the_fastest_man_alive_2022_1", "allamerican_comics_19391948_16"],
  },
  "alan-davis": {
    name: "Alan Davis",
    symbols: ["dc3_super_power_packs_series_batman_year_two", "dc3_super_power_packs_series_jla_the_nail"],
  },
  "alejandro-sanchez": {
    name: "Alejandro Sanchez",
    symbols: ["dark_crisis_on_infinite_earths_1_2022", "absolute_superman_2024_2"],
  },
  "amy-reeder": {
    name: "Amy Reeder",
    symbols: ["absolute_batman_2024_7", "supergirl_2025_4"],
  },
  "arif-prianto": {
    name: "Arif Prianto",
    symbols: ["batman_one_bad_day_penguin_2022_1", "dc_elseworlds_2024_sampler"],
  },
  "brad-anderson": {
    name: "Brad Anderson",
    symbols: ["dc3_super_power_packs_series_aquaman", "superman_2023_1"],
  },
  "bruce-timm": {
    name: "Bruce Timm",
    symbols: ["dc3_super_power_packs_series_batman", "batman_beyond_1999_1"],
  },
  "chris-burnham": {
    name: "Chris Burnham",
    symbols: ["dc3_super_power_packs_series_dawn_of_dc", "absolute_batman_2024_11"],
  },
  "dave-mccaig": {
    name: "Dave McCaig",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_2", "batman_gotham_by_gaslight_the_kryptonian_age_2024_6"],
  },
  "dick-giordano": {
    name: "Dick Giordano",
    symbols: ["the_new_teen_titans_19801988_1", "dc_comics_presents_19781986_26"],
  },
  "fco-plascencia": {
    name: "FCO Plascencia",
    symbols: ["dceased_2019_1", "batman_vol_1_the_court_of_owls"],
  },
  "frank-quitely": {
    name: "Frank Quitely",
    symbols: ["allstar_superman_20052008_1", "absolute_batman_2024_6"],
  },
  "gil-kane": {
    name: "Gil Kane",
    symbols: ["showcase_19561978_22", "green_lantern_19601986_59"],
  },
  "harry-g-peter": {
    name: "Harry G. Peter",
    symbols: ["sensation_comics_19421952_1", "wonder_woman_19421986_1"],
  },
  "jae-lee": {
    name: "Jae Lee",
    symbols: ["red_hood_2025_1", "absolute_batman_2024_2"],
  },
  "joe-kubert": {
    name: "Joe Kubert",
    symbols: ["showcase_19561978_4", "weird_war_tales_19711983_93"],
  },
  "joe-shuster": {
    name: "Joe Shuster",
    symbols: ["action_comics_19382011_23", "superman_1_multiverse_edition"],
  },
  "jonboy-meyers": {
    name: "Jonboy Meyers",
    symbols: ["catwoman_the_legacy_cowl_1", "catwoman_the_legacy_cowl_convention_exclusive"],
  },
  "jorge-jimenez": {
    name: "Jorge Jimenez",
    symbols: ["batman_2025_1_crafted_edition", "allstar_superman"],
  },
  "june-chung": {
    name: "June Chung",
    symbols: ["red_hood_2025_1", "absolute_batman_2024_2"],
  },
  "kelley-jones": {
    name: "Kelley Jones",
    symbols: ["elseworlds_batman_vol_2"],
  },
  "marcelo-maiolo": {
    name: "Marcelo Maiolo",
    symbols: ["dc3_super_power_packs_series_titans_beast_world", "aquaman_2025_1"],
  },
  "marcos-martin": {
    name: "Marcos Martin",
    symbols: ["absolute_batman_2024_8", "absolute_martian_manhunter_2025_1"],
  },
  "mike-mignola": {
    name: "Mike Mignola",
    symbols: ["batman_428_robin_lives_2023_1", "batman_gotham_by_gaslight_1989_1"],
  },
  "mike-sekowsky": {
    name: "Mike Sekowsky",
    symbols: ["justice_league_of_america_19601987_1", "the_brave_and_the_bold_19551983_28"],
  },
  "mike-spicer": {
    name: "Mike Spicer",
    symbols: ["absolute_batman_2024_1", "absolute_wonder_woman_2024_1"],
  },
  "norm-rapmund": {
    name: "Norm Rapmund",
    symbols: ["justice_league_unlimited_2024_6", "summer_of_superman_special_2025_1"],
  },
  "oclair-albert": {
    name: "Oclair Albert",
    symbols: ["the_flash_123_multiverse_edition", "blackest_night_20092010_1"],
  },
  "romulo-fajardo-jr": {
    name: "Romulo Fajardo, Jr.",
    symbols: ["green_arrow_2023_1", "superman_1_multiverse_edition"],
  },
  "simone-di-meo": {
    name: "Simone Di Meo",
    symbols: ["peacemaker_tries_hard_2023_1", "justice_league_unlimited_2024_3"],
  },
  "stan-kaye": {
    name: "Stan Kaye",
    symbols: ["action_comics_19382011_242", "action_comics_19382011_93"],
  },
  "stjepan-sejic": {
    name: "Stjepan Šejić",
    symbols: ["teen_titans_20162020_12", "harleen_2019_1"],
  },
  "tim-sale": {
    name: "Tim Sale",
    symbols: ["batman_the_long_halloween", "batman_dark_victory_issue_0_2025_sdcc_edition_2025_1"],
  },
  "wes-craig": {
    name: "Wes Craig",
    symbols: ["absolute_batman_2024_1", "absolute_wonder_woman_2024_1"],
  },
  "xermanico": {
    name: "Xermanico",
    symbols: ["green_lantern_2023_1", "superman_1_multiverse_edition"],
  },
  "adam-kubert": {
    name: "Adam Kubert",
    symbols: ["batman_19402011_655"],
  },
  "adriano-lucas": {
    name: "Adriano Lucas",
    symbols: ["justice_league_the_atom_project_2025_1"],
  },
  "alex-maleev": {
    name: "Alex Maleev",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_5"],
  },
  "alex-ross": {
    name: "Alex Ross",
    symbols: ["crisis_on_infinite_earths"],
  },
  "andy-owens": {
    name: "Andy Owens",
    symbols: ["dc3_super_power_packs_series_justice_league_vs_suicide_squad"],
  },
  "annette-kwok": {
    name: "Annette Kwok",
    symbols: ["titans_2023_1"],
  },
  "ariel-colon": {
    name: "Ariel Colon",
    symbols: ["batman_dark_victory_issue_0_2025_sdcc_edition_2025_1"],
  },
  "bernard-chang": {
    name: "Bernard Chang",
    symbols: ["dawn_of_dc_wip_covers_2023"],
  },
  "bernie-wrightson": {
    name: "Bernie Wrightson",
    symbols: ["house_of_secrets_19561978_92"],
  },
  "bilquis-evely": {
    name: "Bilquis Evely",
    symbols: ["supergirl_woman_of_tomorrow_20212022_1"],
  },
  "brad-simpson": {
    name: "Brad Simpson",
    symbols: ["absolute_wonder_woman_2024_3"],
  },
  "brett-breeding": {
    name: "Brett Breeding",
    symbols: ["superman_19872006_75"],
  },
  "brian-bolland": {
    name: "Brian Bolland",
    symbols: ["batman_the_killing_joke_1988_1"],
  },
  "bruno-premiani": {
    name: "Bruno Premiani",
    symbols: ["the_brave_and_the_bold_19551983_54"],
  },
  "c-c-beck": {
    name: "C.C. Beck",
    symbols: ["whiz_comics_19401952_2"],
  },
  "charles-paris": {
    name: "Charles Paris",
    symbols: ["the_brave_and_the_bold_19551983_57"],
  },
  "christian-ward": {
    name: "Christian Ward",
    symbols: ["absolute_wonder_woman_2024_4"],
  },
  "clayton-henry": {
    name: "Clayton Henry",
    symbols: ["dc3_super_power_packs_series_titans_beast_world"],
  },
  "curt-swan": {
    name: "Curt Swan",
    symbols: ["action_comics_19382011_242"],
  },
  "dale-keown": {
    name: "Dale Keown",
    symbols: ["aquaman_59_multiverse_edition"],
  },
  "dan-brown": {
    name: "Dan Brown",
    symbols: ["batman_the_joker_the_deadly_duo_2022_1"],
  },
  "dan-panosian": {
    name: "Dan Panosian",
    symbols: ["batman_the_legacy_cowl_2022_3"],
  },
  "dani": {
    name: "DaNi",
    symbols: ["absolute_wonder_woman_2024_3"],
  },
  "daniel-sampere": {
    name: "Daniel Sampere",
    symbols: ["dark_crisis_on_infinite_earths_1_2022"],
  },
  "danny-miki": {
    name: "Danny Miki",
    symbols: ["dc3_super_power_packs_series_aquaman"],
  },
  "dave-stewart": {
    name: "Dave Stewart",
    symbols: ["batman_19402011_655"],
  },
  "dave-wilkins": {
    name: "Dave Wilkins",
    symbols: ["justice_league_unlimited_2024_2"],
  },
  "david-baron": {
    name: "David Baron",
    symbols: ["absolute_batman_2024_11"],
  },
  "declan-shalvey": {
    name: "Declan Shalvey",
    symbols: ["absolute_flash_2025_1"],
  },
  "don-heck": {
    name: "Don Heck",
    symbols: ["wonder_woman_19421986_204"],
  },
  "duncan-fegredo": {
    name: "Duncan Fegredo",
    symbols: ["batman_shadow_of_the_bat_19921999_57"],
  },
  "dustin-nguyen": {
    name: "Dustin Nguyen",
    symbols: ["batman_the_legacy_cowl_the_deluxe_edition"],
  },
  "eber-ferreira": {
    name: "Eber Ferreira",
    symbols: ["the_flash_123_multiverse_edition"],
  },
  "erica-d-urso": {
    name: "Erica D'Urso",
    symbols: ["immortal_legend_batman_2025_1"],
  },
  "everett-hibbard": {
    name: "Everett Hibbard",
    symbols: ["allstar_comics_19401978_3"],
  },
  "francesco-francavilla": {
    name: "Francesco Francavilla",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_3"],
  },
  "francesco-matt-mattina": {
    name: "Francesco MATT Mattina",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_1"],
  },
  "frank-cho": {
    name: "Frank Cho",
    symbols: ["batman_2016_161"],
  },
  "gill-fox": {
    name: "Gill Fox",
    symbols: ["military_comics_19411945_1"],
  },
  "giuseppe-camuncoli": {
    name: "Giuseppe Camuncoli",
    symbols: ["batman_one_bad_day_penguin_2022_1"],
  },
  "glenn-fabry": {
    name: "Glenn Fabry",
    symbols: ["batman_vengeance_of_bane_1992_1"],
  },
  "glenn-whitmore": {
    name: "Glenn Whitmore",
    symbols: ["superman_19872006_75"],
  },
  "greg-smallwood": {
    name: "Greg Smallwood",
    symbols: ["dc_elseworlds_2024_sampler"],
  },
  "hayden-sherman": {
    name: "Hayden Sherman",
    symbols: ["dc3_super_power_packs_series_knight_terrors"],
  },
  "howard-porter": {
    name: "Howard Porter",
    symbols: ["justice_league_unlimited_2024_1"],
  },
  "howard-purcell": {
    name: "Howard Purcell",
    symbols: ["aquaman_19621978_1"],
  },
  "howard-sherman": {
    name: "Howard Sherman",
    symbols: ["more_fun_comics_19361947_73"],
  },
  "ian-bertram": {
    name: "Ian Bertram",
    symbols: ["absolute_martian_manhunter_2025_3"],
  },
  "inhyuk-lee": {
    name: "InHyuk Lee",
    symbols: ["from_the_dc_vault_death_in_the_family_robin_lives_2024_3"],
  },
  "jack-adler": {
    name: "Jack Adler",
    symbols: ["green_lantern_19601986_87"],
  },
  "jack-burnley": {
    name: "Jack Burnley",
    symbols: ["batman_19402011_9"],
  },
  "jack-kirby": {
    name: "Jack Kirby",
    symbols: ["the_demon_19721973_1"],
  },
  "james-grant": {
    name: "James Grant",
    symbols: ["allstar_superman_20052008_1"],
  },
  "jason-keith": {
    name: "Jason Keith",
    symbols: ["aquaman_59_multiverse_edition"],
  },
  "javi-fernandez": {
    name: "Javi Fernandez",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_6"],
  },
  "jeff-spokes": {
    name: "Jeff Spokes",
    symbols: ["absolute_martian_manhunter_2025_2"],
  },
  "jerry-ordway": {
    name: "Jerry Ordway",
    symbols: ["batman_608_multiverse_edition"],
  },
  "jessica-fong": {
    name: "Jessica Fong",
    symbols: ["poison_ivy_2022_1"],
  },
  "jesus-merino": {
    name: "Jesus Merino",
    symbols: ["dc3_super_power_packs_series_justice_league_vs_suicide_squad"],
  },
  "jim-aparo": {
    name: "Jim Aparo",
    symbols: ["aquaman_59_multiverse_edition"],
  },
  "jim-starlin": {
    name: "Jim Starlin",
    symbols: ["dc_comics_presents_19781986_26"],
  },
  "joe-giella": {
    name: "Joe Giella",
    symbols: ["the_flash_19591985_105"],
  },
  "joe-prado": {
    name: "Joe Prado",
    symbols: ["the_flash_123_multiverse_edition"],
  },
  "joe-schuster": {
    name: "Joe Schuster",
    symbols: ["superman_19392011_1"],
  },
  "joelle-jones": {
    name: "Joelle Jones",
    symbols: ["absolute_wonder_woman_2024_2"],
  },
  "john-beatty": {
    name: "John Beatty",
    symbols: ["elseworlds_batman_vol_2"],
  },
  "john-byrne": {
    name: "John Byrne",
    symbols: ["legends_19861987_1"],
  },
  "jon-l-blummer": {
    name: "Jon L. Blummer",
    symbols: ["sensation_comics_19421952_1"],
  },
  "jordie-bellaire": {
    name: "Jordie Bellaire",
    symbols: ["dc3_super_power_packs_series_superman"],
  },
  "jose-villarrubia": {
    name: "Jose Villarrubia",
    symbols: ["absolute_batman_2024_12"],
  },
  "julian-totino-tedesco": {
    name: "Julian Totino Tedesco",
    symbols: ["batman_2025_1"],
  },
  "keron-grant-studio": {
    name: "Keron Grant Studio",
    symbols: ["absolute_superman_2024_4"],
  },
  "kevin-wada": {
    name: "Kevin Wada",
    symbols: ["justice_league_the_atom_project_2025_2"],
  },
  "kyle-hotz": {
    name: "Kyle Hotz",
    symbols: ["batman_the_joker_the_deadly_duo_2022_1"],
  },
  "leandro-fernandez": {
    name: "Leandro Fernandez",
    symbols: ["batman_gotham_by_gaslight_the_kryptonian_age_2024_2"],
  },
  "lee-bermejo": {
    name: "Lee Bermejo",
    symbols: ["from_the_dc_vault_death_in_the_family_robin_lives_2024_4"],
  },
  "lucio-parrillo": {
    name: "Lucio Parrillo",
    symbols: ["justice_league_unlimited_2024_4"],
  },
  "mahmud-asrar": {
    name: "Mahmud Asrar",
    symbols: ["absolute_superman_2024_2"],
  },
  "malcolm-jones-iii": {
    name: "Malcolm Jones III",
    symbols: ["elseworlds_batman_vol_2"],
  },
  "marco-santucci": {
    name: "Marco Santucci",
    symbols: ["batman_the_legacy_cowl_2022_2"],
  },
  "mark-farmer": {
    name: "Mark Farmer",
    symbols: ["dc3_super_power_packs_series_jla_the_nail"],
  },
  "mark-morales": {
    name: "Mark Morales",
    symbols: ["batman_19402011_428"],
  },
  "mat-lopes": {
    name: "Mat Lopes",
    symbols: ["supergirl_woman_of_tomorrow_20212022_1"],
  },
  "matt-taylor": {
    name: "Matt Taylor",
    symbols: ["future_state_wonder_woman_2021_1"],
  },
  "matteo-scalera": {
    name: "Matteo Scalera",
    symbols: ["absolute_superman_2024_1"],
  },
  "max-fiumara": {
    name: "Max Fiumara",
    symbols: ["the_flash_the_fastest_man_alive_2022_1"],
  },
  "michael-cho": {
    name: "Michael Cho",
    symbols: ["batman_2016_159"],
  },
  "mike-perkins": {
    name: "Mike Perkins",
    symbols: ["justice_league_the_atom_project_2025_1"],
  },
  "mike-royer": {
    name: "Mike Royer",
    symbols: ["the_demon_19721973_1"],
  },
  "neal-adams": {
    name: "Neal Adams",
    symbols: ["green_lantern_19601986_87"],
  },
  "nick-cardy": {
    name: "Nick Cardy",
    symbols: ["house_of_mystery_19511983_174"],
  },
  "nick-filardi": {
    name: "Nick Filardi",
    symbols: ["dc3_super_power_packs_series_dawn_of_dc"],
  },
  "nicola-scott": {
    name: "Nicola Scott",
    symbols: ["titans_2023_1"],
  },
  "pablo-m-collar": {
    name: "Pablo M. Collar",
    symbols: ["batman_the_legacy_cowl"],
  },
  "paolo-pantalena": {
    name: "Paolo Pantalena",
    symbols: ["dc3_super_power_packs_series_dawn_of_dc_2"],
  },
  "paul-neary": {
    name: "Paul Neary",
    symbols: ["dc3_super_power_packs_series_batman_year_two"],
  },
  "paul-pope": {
    name: "Paul Pope",
    symbols: ["absolute_batman_2024_12"],
  },
  "puppeteer-lee": {
    name: "Puppeteer Lee",
    symbols: ["absolute_superman_2024_6"],
  },
  "rachel-dodson": {
    name: "Rachel Dodson",
    symbols: ["harley_quinn_20002004_1"],
  },
  "rafa-sandoval": {
    name: "Rafa Sandoval",
    symbols: ["absolute_superman_2024_5"],
  },
  "ramona-fradon": {
    name: "Ramona Fradon",
    symbols: ["the_brave_and_the_bold_19551983_57"],
  },
  "richard-corben": {
    name: "Richard Corben",
    symbols: ["the_spectre_19921998_54"],
  },
  "rick-leonardi": {
    name: "Rick Leonardi",
    symbols: ["from_the_dc_vault_death_in_the_family_robin_lives_2024_2"],
  },
  "rico-renzi": {
    name: "Rico Renzi",
    symbols: ["from_the_dc_vault_death_in_the_family_robin_lives_2024_2"],
  },
  "riley-rossmo": {
    name: "Riley Rossmo",
    symbols: ["absolute_martian_manhunter_2025_6"],
  },
  "rod-reis": {
    name: "Rod Reis",
    symbols: ["the_flash_123_multiverse_edition"],
  },
  "sabine-rich": {
    name: "Sabine Rich",
    symbols: ["batman_2016_161"],
  },
  "sandra-hope": {
    name: "Sandra Hope",
    symbols: ["flashpoint_2011_1"],
  },
  "scorpio-steele": {
    name: "Scorpio Steele",
    symbols: ["dc3_super_power_packs_series_villains"],
  },
  "sean-izaakse": {
    name: "Sean Izaakse",
    symbols: ["green_arrow_2023_1"],
  },
  "shane-davis": {
    name: "Shane Davis",
    symbols: ["batman_19402011_428"],
  },
  "shawn-crystal": {
    name: "Shawn Crystal",
    symbols: ["absolute_batman_2024_10"],
  },
  "sherilyn-van-valkenburgh": {
    name: "Sherilyn Van Valkenburgh",
    symbols: ["elseworlds_batman_vol_2"],
  },
  "stefano-gaudiano": {
    name: "Stefano Gaudiano",
    symbols: ["dc3_super_power_packs_series_villains"],
  },
  "steve-olyoptics-oliff": {
    name: "Steve & Olyoptics Oliff",
    symbols: ["batman_608_multiverse_edition"],
  },
  "tatjana-wood": {
    name: "Tatjana Wood",
    symbols: ["the_new_teen_titans_19801988_1"],
  },
  "terry-dodson": {
    name: "Terry Dodson",
    symbols: ["harley_quinn_20002004_1"],
  },
  "todd-mcfarlane": {
    name: "Todd McFarlane",
    symbols: ["batman_19402011_423"],
  },
  "ulises-arreola": {
    name: "Ulises Arreola",
    symbols: ["absolute_superman_2024_5"],
  },
  "wayne-boring": {
    name: "Wayne Boring",
    symbols: ["action_comics_19382011_93"],
  },
  "wilfredo-torres": {
    name: "Wilfredo Torres",
    symbols: ["dc3_super_power_packs_series_superman"],
  },
  "will-eisner": {
    name: "Will Eisner",
    symbols: ["military_comics_19411945_1"],
  },
  "win-mortimer": {
    name: "Win Mortimer",
    symbols: ["detective_comics_19372011_140"],
  },
  "yasmine-putri": {
    name: "Yasmine Putri",
    symbols: ["absolute_batman_2024_4"],
  },
};
